language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: coverage run --source=Gelatin -m unittest discover -v tests "*Test.py"
after_success:
  coveralls
